// 2020.1.4_vue_slot/hw/src/components/myFooter.vue
<template>
   <footer class="footer">
	            <span class="todo-count">
	            	<strong>{{unChecked}}</strong>
	            	<span>条未选中</span>
                </span>
                <ul 
                    class="filters"
                >
                    <li 
                        v-for="(val,key) in conTent"
                        @click="changeFn(key)"
                    >   
                        <a 
                            href="javascript:;" 
                            :class="  B===key?'selected':''"
                        >{{val}}</a>
                    </li>
                </ul>
               
            </footer>
            
</template>

<script>
    export default {
        props:['pary','unChecked','conTent','B'],
        data(){
            return {
             
            }
        },
        methods: {
            changeFn(key){
                this.$emit('changfn',key)
                
            }
        },
       
    }
</script>

<style lang="scss" scoped>

</style>

// 2020.2.9_react_todo/my-app/src/MyFooter.js
import React, { Component } from 'react';
class MyFooter extends Component {
    constructor(props) {
        super(props);
        this.state = {  };
    }
    render() {
        const {num,hash,chash}=this.props
        return (
            <footer className="footer">
            <span className="todo-count">
                <strong>{num}</strong>
                <span>条未选中</span>
            </span>
            <ul 
                className="filters"
            >
                <li>
                    <a 
                        href="#/all" 
                        className={hash==='/all'?'selected':''}
                        onClick={()=>{chash('/all')}}
                    >全部</a>
                </li>
                <li>
                    <a 
                        href="#/unchecked" 
                        onClick={()=>{chash('/unchecked')}}
                        className={hash==='/unchecked'?'selected':''}
                    >未选中</a>
                </li>
                <li>
                    <a 
                        href="#/checked"
                        onClick={()=>{chash('/checked')}}
                        className={hash==='/checked'?'selected':''}
                       
                    >已选中</a>
                </li>
            </ul>
        </footer>
        );
    }
}

export default MyFooter;
